Сleaning template from relations with wms
Byndyusoft/ui-testing-template pull request #2
Opened 2021-08-27 11:56 UTC by romon2046

2021-08-28 08:19 UTC, sadcitizen commented on .eslintrc.json
> +  "extends": ["@byndyusoft/eslint-config/javascript", "plugin:cypress/recommended", "plugin:prettier/recommended"]
Возможно, нам нужен отдельный eslint-конфиг для cypress в `@byndyusoft/eslint-config`

2021-08-30 07:03 UTC, KillWolfVlad requested changes

2021-08-30 07:03 UTC, KillWolfVlad commented on README.md
> +yarn install <Package name>
`<Package name>` не требуется, достаточно простого `yarn install`

2021-09-09 11:09 UTC, KillWolfVlad approved these changes

2021-10-27 11:43 UTC, merged